GET http://localhost:3000/sclavos HTTP/1.1

GET HTTP/1.1
 
 ### 

GET http://localhost:3000/slcavos/2 HTTP/1.1

###
POST http://localhost:3000/slcavos HTTP/1.1
Content-Content-Type: application/json
{
    
    "nombre":"sergio",
    "edad":14,
    "peso":66
},
###
PuT http://localhost:3000/slcavos/11q HTTP/1.1
Content-Content-Type: application/json
{
    
    "nombre":"sergio",
},